---
- name: "copy latest nginx.repo"
  template:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    mode: 0644

- name: install
  yum:
    name: nginx
    state: present

- name: "add to startup"
  service:
    name: "{{ OS.nginx.name }}"
    enabled: yes
