---
- name: "mbdaemonfinance][Install PlayBook"
  hosts: local
  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  pre_tasks:
    - name: "read billing config"
      include_vars: config/billing.yaml

    - name: "read database config"
      include_vars: config/database.yaml

    - name: "read mbdaemonfinance config"
      include_vars: config/modules/mbdaemonfinance.yaml

    - name: "read OS config"
      include_vars: "config/os/{{ ansible_os_family | lower }}_{{ ansible_distribution_major_version }}.yaml"

    - name: "read timezone"
      shell: timedatectl status | grep 'Time.zone' | awk '{print $3}'
      register: timezone

    - name: "confirm timezone"
      pause:
        prompt: "Please confirm your timezone: {{ timezone.stdout }} ?\nPress 'enter' to continue or 'Ctrl+c' and then 'a' to abort"

    - name: "setup default timezone"
      set_fact:
        timezone:
          stdout: "Europe/Kiev"
      when: '"/" not in timezone.stdout'

    - name: "create {{ billing.dirs.tmp }}"
      file:
        path: "{{ billing.dirs.tmp }}"
        owner: root
        group: root
        mode: 0755
        state: directory
  roles:
   - requirements
   - selinux
   - packages
   - php
   - disable_eval
   - ioncube
   - settings
   - database_connect
   - mbdaemonfinance
   - final
