---
- name: "update {{ mbnotify.dirs.module }} {{ mbnotify.dirs.production }}"
  command: "/bin/bash {{ mbnotify.files.updates }}"
  args:
    chdir: "{{ billing.dirs.home }}/{{ mbnotify.dirs.module }}/{{ mbnotify.dirs.production }}/{{ mbnotify.dirs.updates }}"
  ignore_errors: yes

- name: "update {{ mbnotify.dirs.module }} {{ mbnotify.dirs.testing }}"
  command: "/bin/bash {{ mbnotify.files.testing }}"
  args:
    chdir: "{{ billing.dirs.home }}/{{ mbnotify.dirs.module }}/{{ mbnotify.dirs.testing }}/{{ mbnotify.dirs.updates }}"
  ignore_errors: yes
