---
- name: "replace {{ mbdaemonbot.dirs.production }} cofig values"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbdaemonbot.dirs.module }}/{{ mbdaemonbot.dirs.production }}/{{ mbdaemonbot.dirs.config }}/{{ mbdaemonbot.files.config }}"
    regexp: "{{ item.name }}"
    replace: "{{ item.value }}"
  with_items:
    - { name: '{server_host}', value: "{{ billing.mysql_server }}" }
    - { name: '{username}', value: "{{ mbdaemonbot.software.database.mysql_user }}" }
    - { name: '{database}', value: "{{ mysql.database }}" }
    - { name: '{log_general}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonbot.dirs.module }}/{{ mbdaemonbot.files.log_main }}" }
    - { name: '{log_debug}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonbot.dirs.module }}/{{ mbdaemonbot.files.log_debug }}" }
    - { name: '{timezone}', value: "{{ timezone.stdout }}" }
    - { name: '{mbdaemonbot_pid}', value: "{{ mbdaemonbot.params.production.pid }}" }
    - { name: '{mbdaemonbot_ip}', value: "{{ mbdaemonbot.params.production.ip }}" }
    - { name: '{mbdaemonbot_port}', value: "{{ mbdaemonbot.params.production.port }}" }

- name: "replace mysql password"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbdaemonbot.dirs.module }}/{{ mbdaemonbot.dirs.production }}/{{ mbdaemonbot.dirs.config }}/{{ mbdaemonbot.files.config }}"
    regexp: "{password}"
    replace: "{{ mbdaemonbot.software.database.mysql_pass }}"
  when: mbdaemonbot.software.database.mysql_pass != ""
  no_log: true

- name: "replace {{ mbdaemonbot.dirs.testing }} cofig values"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbdaemonbot.dirs.module }}/{{ mbdaemonbot.dirs.testing }}/{{ mbdaemonbot.dirs.config }}/{{ mbdaemonbot.files.config }}"
    regexp: "{{ item.name }}"
    replace: "{{ item.value }}"
  with_items:
    - { name: '{server_host}', value: "{{ billing.mysql_server }}" }
    - { name: '{username}', value: "{{ mbdaemonbot.software.database.mysql_user }}" }
    - { name: '{database}', value: "{{ mysql.testing }}" }
    - { name: '{log_general}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonbot.dirs.module }}/{{ mbdaemonbot.files.log_main }}" }
    - { name: '{log_debug}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonbot.dirs.module }}/{{ mbdaemonbot.files.log_debug }}" }
    - { name: '{timezone}', value: "{{ timezone.stdout }}" }
    - { name: '{mbdaemonbot_pid}', value: "{{ mbdaemonbot.params.testing.pid }}" }
    - { name: '{mbdaemonbot_ip}', value: "{{ mbdaemonbot.params.production.ip }}" }
    - { name: '{mbdaemonbot_port}', value: "{{ mbdaemonbot.params.production.port }}" }

- name: "replace mysql password"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbdaemonbot.dirs.module }}/{{ mbdaemonbot.dirs.testing }}/{{ mbdaemonbot.dirs.config }}/{{ mbdaemonbot.files.config }}"
    regexp: "{password}"
    replace: "{{ mbdaemonbot.software.database.mysql_pass }}"
  when: mbdaemonbot.software.database.mysql_pass != ""
  no_log: true
