---
- name: "add records"
  blockinfile:
    path: "{{ OS.hosts }}"
    block: |
      127.0.0.1 {{ mbadmin.software.nginx.subdomain.production }}.{{ billing.domain }}
      127.0.0.1 {{ mbadmin.software.nginx.subdomain.testing }}.{{ billing.domain }}
    marker: "# {mark} mbadmin DEFAULT RECORDS"
