---
- name: "copy {{ mbqueue.files.archive }}"
  copy:
    src: "{{ mbqueue.files.archive }}"
    dest: "{{ billing.dirs.tmp }}/{{ mbqueue.files.archive }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: "unpack {{ mbqueue.files.archive }}"
  unarchive:
    src: "{{ billing.dirs.tmp }}/{{ mbqueue.files.archive }}"
    dest: "{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ item }}"
  with_items:
    - "{{ mbqueue.dirs.production }}"
    - "{{ mbqueue.dirs.testing }}"

- name: "copy {{ mbqueue.files.config }} files"
  copy:
    src: "{{ mbqueue.files.config }}"
    dest: "{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ item }}/{{ mbqueue.dirs.config }}/{{ mbqueue.files.config }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items:
    - "{{ mbqueue.dirs.production }}"
    - "{{ mbqueue.dirs.testing }}"

- name: "create log files"
  file:
    path: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbqueue.dirs.module }}/{{ item }}"
    state: touch
    owner: root
    group: root
    mode: u=rw,g=rw,o=rw
  with_items:
    - "{{ mbqueue.files.log_main }}"
    - "{{ mbqueue.files.log_debug }}"
    - "{{ mbqueue.files.log_update }}"

- name: "setup updater"
  template:
    src: "{{ item.file }}"
    dest: "{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ item.dst }}/{{ mbqueue.dirs.updates }}/{{ item.file }}"
    owner: root
    group: root
    mode: u=rw,g=rx,o=rx
  with_items:
    - { file: "{{ mbqueue.files.updates }}", dst: "{{ mbqueue.dirs.production }}" }
    - { file: "{{ mbqueue.files.testing }}", dst: "{{ mbqueue.dirs.testing }}" }

- name: "register {{ mbqueue.dirs.production }} path"
  set_fact: module_path="{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ mbqueue.dirs.production }}"

- name: "setup {{ mbqueue.dirs.production }} scripts"
  template:
    src: "scripts/{{ item }}"
    dest: "{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ mbqueue.dirs.production }}/scripts/{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ mbqueue.files.scripts }}"

- name: "register {{ mbqueue.dirs.testing }} path"
  set_fact: module_path="{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ mbqueue.dirs.testing }}"

- name: "setup {{ mbqueue.dirs.production }} scripts"
  template:
    src: "scripts/{{ item }}"
    dest: "{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ mbqueue.dirs.testing }}/scripts/{{ item }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ mbqueue.files.scripts }}"
