---
- name: "copy {{ mbqueue.files.archive }}"
  copy:
    src: "{{ mbqueue.files.archive }}"
    dest: "{{ billing.dirs.tmp }}/{{ mbqueue.files.archive }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: "unpack {{ mbqueue.files.archive }}"
  unarchive:
    src: "{{ billing.dirs.tmp }}/{{ mbqueue.files.archive }}"
    dest: "{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ item }}"
  with_items:
    - "{{ mbqueue.dirs.production }}"
    - "{{ mbqueue.dirs.testing }}"

- name: "copy {{ mbqueue.files.config }} files"
  copy:
    src: "{{ mbqueue.files.config }}"
    dest: "{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ item }}/{{ mbqueue.dirs.config }}/{{ mbqueue.files.config }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items:
    - "{{ mbqueue.dirs.production }}"
    - "{{ mbqueue.dirs.testing }}"

- name: "create log files"
  file:
    path: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbqueue.dirs.module }}/{{ item }}"
    state: touch
    owner: root
    group: root
    mode: u=rw,g=rw,o=rw
  with_items:
    - "{{ mbqueue.files.log_main }}"
    - "{{ mbqueue.files.log_debug }}"
    - "{{ mbqueue.files.log_update }}"

- name: "add updater"
  template:
    src: "{{ item.src }}"
    dest: "{{ billing.dirs.home }}/{{ mbqueue.dirs.module }}/{{ item.path }}/{{ mbqueue.dirs.updates }}/{{ item.dest }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - { src: "update_production.sh", dest: "{{ mbqueue.files.updates }}", path: "{{ mbqueue.dirs.production }}" }
    - { src: "update_testing.sh", dest: "{{ mbqueue.files.testing }}", path: "{{ mbqueue.dirs.testing }}" }
