---
- include_tasks: permission.yml
- include_tasks: database.yml
  when: hostvars[inventory_hostname].root_passwd is defined
- include_tasks: radius.yml
  when: mbradius is defined
- include_tasks: mbcore.yml
  when: mbcore is defined
- include_tasks: mbsql.yml
  when: mbsql is defined
- include_tasks: mbadmin.yml
  when: mbadmin is defined
- include_tasks: mbcabinet.yml
  when: mbcabinet is defined
- include_tasks: mbcabapi.yml
  when: mbcabapi is defined
- include_tasks: mbpaygw.yml
  when: mbpaygw is defined
- include_tasks: mbcron.yml
  when: mbcron is defined
