---
- name: "copy default {{ billing.dirs.scripts }}"
  copy:
    src: "scripts/{{ item }}"
    dest: "{{ billing.dirs.home }}/{{ billing.dirs.files }}/{{ billing.dirs.scripts }}/{{ item }}"
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
  with_items:
    - "cpu_info.sh"
    - "current_ram.sh"
    - "disk_partitions.sh"
    - "logged_in_users.sh"
    - "mb_event_iptv_add.sh"
    - "mb_event_iptv_del.sh"
    - "mb_event_port_change.sh"
    - "mb_event_realip_change.sh"
    - "mb_event_switch_change.sh"
    - "mb_event_ticket_close.sh"
    - "mb_event_ticket_message.sh"
    - "mb_event_ticket_open.sh"
    - "onoff_user_event.sh"
    - "payment_event.sh"
    - "pcq.sh"
    - "pinger.sh"
    - "pingerarp.sh"
    - "port_restart_event.sh"
    - "ram_info.sh"
    - "tarif_change_event.sh"
