---
- name: "make symlink"
  file:
    src: "{{ OS.php.dirs.mods }}/ioncube.ini"
    dest: "{{ item }}"
    mode: 0644
    state: link
  with_items:
    - "{{ OS.php.dirs.conf }}/cli/conf.d/04-ioncube.ini"
    - "{{ OS.fpm.dirs.conf }}/fpm/conf.d/04-ioncube.ini"
  when: ansible_os_family | lower == 'debian'

- name: "restart php-fpm service"
  service:
    name: "{{ OS.fpm.name }}"
    state: restarted

- name: "chmod"
  file: 
    dest: "{{ OS.php.dirs.mods }}/ioncube.ini"
    mode: 0644
