---
- name: "replace radiusd.conf params"
  replace:
    path: "{{ OS.radius.dirs.conf }}/radiusd.conf"
    regexp: "{radius_daemon}"
    replace: "{{ OS.radius.name }}"

- name: "replace sql.conf params"
  replace:
    path: "{{ OS.radius.dirs.conf }}/sql.conf"
    regexp: "{{ item.param }}"
    replace: "{{ item.value }}"
  loop:
    - { param: "{db_address}",      value: "{{ billing.mysql_server }}" }
    - { param: "{db_name}",         value: "{{ mysql.database }}" }
    - { param: "{login}",           value: "{{ mbradius.software.database.mysql_user }}" }
