---
- name: "update {{ mbtvdaemon.dirs.module }} {{ mbtvdaemon.dirs.production }}"
  command: "/bin/bash {{ mbtvdaemon.files.updates }}"
  args:
    chdir: "{{ billing.dirs.home }}/{{ mbtvdaemon.dirs.module }}/{{ mbtvdaemon.dirs.production }}/{{ mbtvdaemon.dirs.updates }}"
  ignore_errors: yes

- name: "update {{ mbtvdaemon.dirs.module }} {{ mbtvdaemon.dirs.testing }}"
  command: "/bin/bash {{ mbtvdaemon.files.testing }}"
  args:
    chdir: "{{ billing.dirs.home }}/{{ mbtvdaemon.dirs.module }}/{{ mbtvdaemon.dirs.testing }}/{{ mbtvdaemon.dirs.updates }}"
  ignore_errors: yes
