---
- name: "copy {{ mbcore.files.archive }}"
  copy:
    src: "{{ mbcore.files.archive }}"
    dest: "{{ billing.dirs.tmp }}/{{ mbcore.files.archive }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: "unpack {{ mbcore.files.archive }}"
  unarchive:
    src: "{{ billing.dirs.tmp }}/{{ mbcore.files.archive }}"
    dest: "{{ billing.dirs.home }}/{{ mbcore.dirs.module }}/{{ item }}"
  with_items:
    - "{{ mbcore.dirs.production }}"
    - "{{ mbcore.dirs.testing }}"

- name: "copy {{ mbcore.files.config }} files"
  copy:
    src: "{{ mbcore.files.config }}"
    dest: "{{ billing.dirs.home }}/{{ mbcore.dirs.module }}/{{ item }}/{{ mbcore.dirs.config }}/{{ mbcore.files.config }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items:
    - "{{ mbcore.dirs.production }}"
    - "{{ mbcore.dirs.testing }}"

- name: "create log files"
  file:
    path: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbcore.dirs.module }}/{{ item }}"
    state: touch
    owner: root
    group: root
    mode: u=rw,g=rw,o=rw
  with_items:
    - "{{ mbcore.files.log_main }}"
    - "{{ mbcore.files.log_debug }}"
    - "{{ mbcore.files.log_update }}"

- name: "add updater"
  template:
    src: "{{ item.src }}"
    dest: "{{ billing.dirs.home }}/{{ mbcore.dirs.module }}/{{ item.path }}/{{ mbcore.dirs.updates }}/{{ item.dest }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - { src: "update_production.sh", dest: "{{ mbcore.files.updates }}", path: "{{ mbcore.dirs.production }}" }
    - { src: "update_testing.sh", dest: "{{ mbcore.files.testing }}", path: "{{ mbcore.dirs.testing }}" }
