---
- name: "update {{ mbcore.dirs.module }} {{ mbcore.dirs.production }}"
  command: "/bin/bash {{ mbcore.files.updates }}"
  args:
    chdir: "{{ billing.dirs.home }}/{{ mbcore.dirs.module }}/{{ mbcore.dirs.production }}/{{ mbcore.dirs.updates }}"
  ignore_errors: yes

- name: "update {{ mbcore.dirs.module }} {{ mbcore.dirs.testing }}"
  command: "/bin/bash {{ mbcore.files.testing }}"
  args:
    chdir: "{{ billing.dirs.home }}/{{ mbcore.dirs.module }}/{{ mbcore.dirs.testing }}/{{ mbcore.dirs.updates }}"
  ignore_errors: yes
