---
- name: "generate password"
  shell: "bash roles/generatepasswd.sh > {{ billing.dirs.tmp }}/mbadmin_stuff_user"

- name: "copy password into variable"
  set_fact:
    mbadmin_stuff_user: "{{ lookup('file', '{{ billing.dirs.tmp }}/mbadmin_stuff_user') }}"

- name: "update password for mbadmin"
  command: mysql --defaults-file="{{ billing.mysql_connect }}" {{ mysql.database }} -e "UPDATE stuff_personal SET pass=MD5('{{ mbadmin_stuff_user }}') WHERE login='admin'"

- name: "update password for mbadmin"
  command: mysql --defaults-file="{{ billing.mysql_connect }}" {{ mysql.testing }} -e "UPDATE stuff_personal SET pass=MD5('{{ mbadmin_stuff_user }}') WHERE login='admin'"

- name: "add info to {{ billing.dirs.home }}/mbadmin.info"
  blockinfile:
    path: "{{ billing.dirs.home }}/mbadmin.info"
    block: |
      url_production= https://{{ mbadmin.software.nginx.subdomain.production }}.{{ billing.domain }}
      url_testing= https://{{ mbadmin.software.nginx.subdomain.testing }}.{{ billing.domain }}
      login=admin
      password={{ mbadmin_stuff_user }}
    marker: "# {mark} mbadmin web info"
