---
- name: "chmod log file"
  file:
    path: "{{ OS.database.percona.dirs.logs }}/mysql.err"
    owner: mysql
    group: mysql
    mode: '0644'

- name: "check {{ OS.database.percona.name }} service is started"
  service:
    name: "{{ OS.database.percona.name }}"
    state: started

- name: "check that we need change password"
  block:
    - name: "check that we dont change password before"
      stat:
        path: "{{ billing.dirs.tmp }}/connect_password_changed"
      register: connect_password_changed

    - name: "get temporary password from mysql log"
      shell: "cat {{ OS.database.percona.dirs.logs }}/{{ OS.database.percona.firstrun_pwd }} | sed -n 's/.*temporary password is generated for root@localhost: //p' | tail -n1"
      register: temporary_password

    - name: "[temporary] set new root password"
      shell: mysql -u root -p"{{ temporary_password.stdout }}" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ hostvars[inventory_hostname].root_passwd }}';"
      when:
        - OS.database.percona.version == 80 or OS.database.percona.version == 8.0
        - connect_password_changed.stat.exists == false
        - temporary_password.stdout | length > 0

    - name: "[empty] set new root password"
      shell: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ hostvars[inventory_hostname].root_passwd }}';"
      when:
        - OS.database.percona.version == 80 or OS.database.percona.version == 8.0
        - temporary_password.stdout | length == 0
        - connect_password_changed.stat.exists == false

    - name: "mark connect password is changed"
      file:
        path: "{{ billing.dirs.tmp }}/connect_password_changed"
        state: touch
      when: connect_password_changed.stat.exists == false
  when: mysql.pass == ''
