---
- name: "create db roles"
  shell: mysql --defaults-file="{{ billing.mysql_connect }}" -e "CREATE ROLE {{ item }};"
  ignore_errors: yes
  failed_when: false
  with_items:
    - "{{ mbadmin.software.database.mysql_role }}"
    - "{{ mbcore.software.database.mysql_role }}"
    - "{{ mbpaygw.software.database.mysql_role }}"
    - "{{ mbradius.software.database.mysql_role }}"
    - "{{ mbcabinet.software.database.mysql_role }}"
    - "{{ mbcron.software.database.mysql_role }}"
    - "{{ mbsql.software.database.mysql_role }}"
    - "{{ mbcabapi.software.database.mysql_role }}"
