---
- name: "create db roles"
  shell: mysql --defaults-file="{{ billing.mysql_connect }}" -e "CREATE ROLE {{ item }};"
  ignore_errors: yes
  failed_when: false
  with_items:
    - "{{ mbradius.software.database.mysql_role }}"
    - "{{ mbadmin.software.database.mysql_role }}"
    - "{{ mbcabapi.software.database.mysql_role }}"
    - "{{ mbcabinet.software.database.mysql_role }}"
    - "{{ mbconsole.software.database.mysql_role }}"
    - "{{ mbcron.software.database.mysql_role }}"
    - "{{ mbdaemonacs.software.database.mysql_role }}"
    - "{{ mbdaemonapi.software.database.mysql_role }}"
    - "{{ mbdaemonbot.software.database.mysql_role }}"
    - "{{ mbdaemoncctv.software.database.mysql_role }}"
    - "{{ mbdaemoncore.software.database.mysql_role }}"
    - "{{ mbdaemonextbill.software.database.mysql_role }}"
    - "{{ mbdaemonfailover.software.database.mysql_role }}"
    - "{{ mbdaemonfinance.software.database.mysql_role }}"
    - "{{ mbdaemonfiscalization.software.database.mysql_role }}"
    - "{{ mbdaemonmessenger.software.database.mysql_role }}"
    - "{{ mbdaemonnotify.software.database.mysql_role }}"
    - "{{ mbdaemononureg.software.database.mysql_role }}"
    - "{{ mbdaemonosbb.software.database.mysql_role }}"
    - "{{ mbdaemonpon.software.database.mysql_role }}"
    - "{{ mbdaemonqueue.software.database.mysql_role }}"
    - "{{ mbdaemonshop.software.database.mysql_role }}"
    - "{{ mbdaemonsnmp.software.database.mysql_role }}"
    - "{{ mbdaemontasks.software.database.mysql_role }}"
    - "{{ mbdaemontrapd.software.database.mysql_role }}"
    - "{{ mbdaemontv.software.database.mysql_role }}"
    - "{{ mbdaemonvoip.software.database.mysql_role }}"
    - "{{ mbhookacs.software.database.mysql_role }}"
    - "{{ mbhookapi.software.database.mysql_role }}"
    - "{{ mbhookbots.software.database.mysql_role }}"
    - "{{ mbhookcctv.software.database.mysql_role }}"
    - "{{ mbhookext.software.database.mysql_role }}"
    - "{{ mbhookextbill.software.database.mysql_role }}"
    - "{{ mbhookfailover.software.database.mysql_role }}"
    - "{{ mbhookfiscalization.software.database.mysql_role }}"
    - "{{ mbhookmessenger.software.database.mysql_role }}"
    - "{{ mbhookonureg.software.database.mysql_role }}"
    - "{{ mbhookosbb.software.database.mysql_role }}"
    - "{{ mbhookpaygw.software.database.mysql_role }}"
    - "{{ mbhookpon.software.database.mysql_role }}"
    - "{{ mbhookshop.software.database.mysql_role }}"
    - "{{ mbhooksorm.software.database.mysql_role }}"
    - "{{ mbhooktasks.software.database.mysql_role }}"
    - "{{ mbhooktrapd.software.database.mysql_role }}"
    - "{{ mbhooktv.software.database.mysql_role }}"
    - "{{ mbhookunsafeext.software.database.mysql_role }}"
    - "{{ mbhookvoip.software.database.mysql_role }}"
    - "{{ mbsql.software.database.mysql_role }}"
