---
- name: "grant rights to {{ mbradius.software.database.mysql_role }} role"
  shell: mysql --defaults-file="{{ billing.mysql_connect }}" -e "GRANT SELECT ON {{ item }}.radnas TO '{{ mbradius.software.database.mysql_role }}'"
  with_items:
    - "{{ mysql.database }}"
    - "{{ mysql.testing }}"
  no_log: true
