---
- name: "read modules config"
  include_vars: "config/modules/{{ item }}.yaml"
  with_items:
    - "mbadmin"
    - "mbkernel"
    - "mbpayments"
    - "mbradius"
    - "mbstat"
    - "mbqueue"
    - "mbdbupdate"
    - "mbcabapi"

- include_tasks: 10_create_files_and_folders.yml
- include_tasks: 20_connect_password.yml
- include_tasks: "30_install_percona_{{ ansible_os_family | lower }}{{ ansible_distribution_major_version }}.yml"
  when: billing.install_percona

- include_tasks: 40_change_connect_password.yml
  when: billing.install_percona

- include_tasks: 50_copy_dump.yml
- include_tasks: 55_check_mysql_connect.yml

- name: "check {{ billing.mysql_connect }} exists"
  stat:
    path: "{{ billing.mysql_connect }}"
  register: mysql_connect

- name: "billing database"
  block:
    - include_tasks: 60_create_db.yml
    - include_tasks: 61_import_db.yml
    - include_tasks: 70_delete_users.yml
    - include_tasks: 80_create_roles.yml
    - include_tasks: 81_role_mbadmin_rights.yml
    - include_tasks: 82_role_mbstat_rights.yml
    - include_tasks: 83_role_mbkernel_rights.yml
    - include_tasks: 84_role_mbradius_rights.yml
    - include_tasks: 85_role_mbpayments_rights.yml
    - include_tasks: 86_role_mbqueue_rights.yml
    - include_tasks: 87_role_mbdbupdate_rights.yml
    - include_tasks: 88_role_mbcabapi_rights.yml
    - include_tasks: 100_create_mbadmin_user.yml
    - include_tasks: 101_create_mbstat_user.yml
    - include_tasks: 102_create_mbkernel_user.yml
    - include_tasks: 103_create_mbradius_user.yml
    - include_tasks: 104_create_mbpayments_user.yml
    - include_tasks: 105_create_mbqueue_user.yml
    - include_tasks: 106_create_mbdbupdate_user.yml
    - include_tasks: 107_create_mbcabapi_user.yml
    - include_tasks: 110_change_mbadmin_password.yml
  when: mysql_connect.stat.exists

- include_tasks: 120_systemd.yml
  when: billing.install_percona
