---
- name: "read modules config"
  include_vars: "config/modules/{{ item }}.yaml"
  with_items:
    - "mbradius"
    - "mbadmin"
    - "mbcabapi"
    - "mbcabinet"
    - "mbconsole"
    - "mbcron"
    - "mbdaemonacs"
    - "mbdaemonapi"
    - "mbdaemonbot"
    - "mbdaemoncctv"
    - "mbdaemoncore"
    - "mbdaemonextbill"
    - "mbdaemonfailover"
    - "mbdaemonfinance"
    - "mbdaemonfiscalization"
    - "mbdaemonmessenger"
    - "mbdaemonnotify"
    - "mbdaemononureg"
    - "mbdaemonosbb"
    - "mbdaemonpon"
    - "mbdaemonqueue"
    - "mbdaemonshop"
    - "mbdaemonsnmp"
    - "mbdaemontasks"
    - "mbdaemontrapd"
    - "mbdaemontv"
    - "mbdaemonvoip"
    - "mbhookacs"
    - "mbhookapi"
    - "mbhookbots"
    - "mbhookcctv"
    - "mbhookext"
    - "mbhookextbill"
    - "mbhookfailover"
    - "mbhookfiscalization"
    - "mbhookmessenger"
    - "mbhookonureg"
    - "mbhookosbb"
    - "mbhookpaygw"
    - "mbhookpon"
    - "mbhookshop"
    - "mbhooksorm"
    - "mbhooktasks"
    - "mbhooktrapd"
    - "mbhooktv"
    - "mbhookunsafeext"
    - "mbhookvoip"
    - "mbsql"

- include_tasks: 10_create_files_and_folders.yml

- name: "install_percona"
  block:
    - include_tasks: 20_connect_password.yml
    - include_tasks: "30_install_percona_{{ ansible_os_family | lower }}{{ ansible_distribution_major_version }}.yml"
    - include_tasks: 40_change_connect_password.yml
  when: billing.install_percona

- include_tasks: 50_copy_dump.yml
- include_tasks: 55_check_mysql_connect.yml

- name: "check {{ billing.mysql_connect }} exists"
  stat:
    path: "{{ billing.mysql_connect }}"
  register: mysql_connect

- name: "billing database"
  block:
    - include_tasks: 60_create_db.yml
    - include_tasks: 61_import_db.yml
    - include_tasks: 70_delete_users.yml
    - include_tasks: 80_create_roles.yml
    - include_tasks: 81_role_mbadmin_rights.yml
    - include_tasks: 82_role_mbcabinet_rights.yml
    - include_tasks: 83_role_mbdaemoncore_rights.yml
    - include_tasks: 84_role_mbradius_rights.yml
    - include_tasks: 85_role_mbhookpaygw_rights.yml
    - include_tasks: 86_role_mbcron_rights.yml
    - include_tasks: 87_role_mbsql_rights.yml
    - include_tasks: 88_role_mbcabapi_rights.yml
    - include_tasks: 89_role_mbdaemonqueue_rights.yml
    - include_tasks: 90_role_mbdaemonnotify_rights.yml
    - include_tasks: 91_role_mbdaemontv_rights.yml
    - include_tasks: 92_role_mbdaemonbot_rights.yml
    - include_tasks: 93_role_mbdaemonfinance_rights.yml
    - include_tasks: 94_role_mbdaemonmessenger_rights.yml
    - include_tasks: 200_create_mbadmin_user.yml
    - include_tasks: 201_create_mbcabinet_user.yml
    - include_tasks: 202_create_mbdaemoncore_user.yml
    - include_tasks: 203_create_mbradius_user.yml
    - include_tasks: 204_create_mbhookpaygw_user.yml
    - include_tasks: 205_create_mbcron_user.yml
    - include_tasks: 206_create_mbsql_user.yml
    - include_tasks: 207_create_mbcabapi_user.yml
    - include_tasks: 208_create_mbdaemonqueue_user.yml
    - include_tasks: 209_create_mbdaemonnotify_user.yml
    - include_tasks: 210_create_mbdaemontv_user.yml
    - include_tasks: 211_create_mbdaemonbot_user.yml
    - include_tasks: 212_create_mbdaemonfinance_user.yml
    - include_tasks: 213_create_mbdaemonmessenger_user.yml
    - include_tasks: 300_change_mbadmin_password.yml
  when: mysql_connect.stat.exists

- include_tasks: 310_systemd.yml
  when: billing.install_percona
