---
- name: "copy {{ mbdaemoncore.files.archive }}"
  copy:
    src: "{{ mbdaemoncore.files.archive }}"
    dest: "{{ billing.dirs.tmp }}/{{ mbdaemoncore.files.archive }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: "unpack {{ mbdaemoncore.files.archive }}"
  unarchive:
    src: "{{ billing.dirs.tmp }}/{{ mbdaemoncore.files.archive }}"
    dest: "{{ billing.dirs.home }}/{{ mbdaemoncore.dirs.module }}/{{ item }}"
  with_items:
    - "{{ mbdaemoncore.dirs.production }}"
    - "{{ mbdaemoncore.dirs.testing }}"

- name: "copy {{ mbdaemoncore.files.config }} files"
  copy:
    src: "{{ mbdaemoncore.files.config }}"
    dest: "{{ billing.dirs.home }}/{{ mbdaemoncore.dirs.module }}/{{ item }}/{{ mbdaemoncore.dirs.config }}/{{ mbdaemoncore.files.config }}"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items:
    - "{{ mbdaemoncore.dirs.production }}"
    - "{{ mbdaemoncore.dirs.testing }}"

- name: "create log files"
  file:
    path: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemoncore.dirs.module }}/{{ item }}"
    state: touch
    owner: root
    group: root
    mode: u=rw,g=rw,o=rw
  with_items:
    - "{{ mbdaemoncore.files.log_main }}"
    - "{{ mbdaemoncore.files.log_debug }}"
    - "{{ mbdaemoncore.files.log_update }}"

- name: "add updater"
  template:
    src: "{{ item.src }}"
    dest: "{{ billing.dirs.home }}/{{ mbdaemoncore.dirs.module }}/{{ item.path }}/{{ mbdaemoncore.dirs.updates }}/{{ item.dest }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - { src: "update_production.sh", dest: "{{ mbdaemoncore.files.updates }}", path: "{{ mbdaemoncore.dirs.production }}" }
    - { src: "update_testing.sh", dest: "{{ mbdaemoncore.files.testing }}", path: "{{ mbdaemoncore.dirs.testing }}" }

- name: "add event scripts"
  copy:
    src: "event_scripts/{{ item }}.sh"
    dest: "{{ billing.dirs.home }}/{{ billing.dirs.files }}/{{ billing.dirs.scripts }}/{{ mbdaemoncore.dirs.module }}/{{ item }}.sh"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - "{{ mbdaemoncore.files.event_scripts }}"
