mbadmin:
  software:
    database:
      mysql_user: "mbadmin"
      mysql_role: "role_mbadmin"
      # Пароль пользователя
      # если пароль указан, то он будет использоваться при попытке подключения к базе (пользователь должен быть создан заранее)
      # если значение пустое, пароль будет сгенерирован (если база данных на одном сервере с модулем)
      mysql_pass: ""
      # адрес с которого будет подключаться модуль к MySQL серверу
      client_ip: "127.0.0.1"
      # взять IP адрес из переменной ansible_default_ipv4, в таком слчаи client_ip будет проигнорирован
      use_ansible_default_ipv4: true
    nginx:
      subdomain:
        # поддомен админки, если основной домен ispnet.demo
        # то получится:
        #   рабочая версия: admin.ispnet.demo
        #   тестовая версия: test.admin.ispnet.demo
        production: "admin"
        testing: "test.admin"
    fpm:
      production:
        pool_name: "mbadmin_production"
        pool_file: "mbadmin_production.conf"
        socket: "/var/run/php-fpm_mbadmin_production.sock"
      testing:
        pool_name: "mbadmin_testing"
        pool_file: "mbadmin_testing.conf"
        socket: "/var/run/php-fpm_mbadmin_testing.sock"
  dirs:
    module: "mbadmin"
    chroot: "chroot"
    www: "/var/www"
    config: "config"
    production: "production"
    testing: "testing"
    updates: "updates"
  files:
    dashboard_scripts: ["cpu_info", "current_ram", "disk_partitions", "logged_in_users", "ram_info"]
    event_scripts: ["mb_event_device_add", "mb_event_device_del", "mb_event_iptv_add", "mb_event_iptv_del", "mb_event_iptv_disable", "mb_event_iptv_enable", "mb_event_payment", "mb_event_port_change", "mb_event_port_restart", "mb_event_realip_change", "mb_event_switch_change", "mb_event_tarif_change", "mb_event_ticket_close", "mb_event_ticket_message", "mb_event_ticket_open", "mb_event_user_blocked", "mb_event_user_state_change", "mb_event_user_unblocked"]
    archive_backend: "mbadmin.tar.gz"
    archive_frontend: "mbfront.tar.gz"
    update_backend: "mbadmin_backend_update.sh"
    update_frontend: "mbadmin_frontend_update.sh"
    testing_backend: "mbadmin_backend_testing.sh"
    testing_frontend: "mbadmin_frontend_testing.sh"
    config: "config.xml"
    log_main: "general.log"
    log_debug: "debug.log"
    log_update: "update.log"
  requirements:
    ram: 1864
    cores: 2
