mbcabapi:
  software:
    database:
      mysql_user: "mbcabapi"
      mysql_role: "role_mbcabapi"
      # Пароль пользователя
      # если пароль указан, то он будет использоваться при попытке подключения к базе (пользователь должен быть создан заранее)
      # если значение пустое, пароль будет сгенерирован (если база данных на одном сервере с модулем)
      mysql_pass: ""
      # адрес с которого будет подключаться модуль к MySQL серверу
      client_ip: "127.0.0.1"
      # взять IP адрес из переменной ansible_default_ipv4, в таком слчаи client_ip будет проигнорирован
      use_ansible_default_ipv4: true
    nginx:
      subdomain:
        # поддомен админки, если основной домен ispnet.demo
        # то получится:
        #   рабочая версия: cabapi.ispnet.demo
        #   тестовая версия: test.cabapi.ispnet.demo
        production: "cabapi"
        testing: "test.cabapi"
    fpm:
      production:
        pool_name: "mbcabapi_production"
        pool_file: "mbcabapi_production.conf"
        socket: "/var/run/php-fpm_mbcabapi_production.sock"
      testing:
        pool_name: "mbcabapi_testing"
        pool_file: "mbcabapi_testing.conf"
        socket: "/var/run/php-fpm_mbcabapi_testing.sock"
  dirs:
    module: "mbcabapi"
    chroot: "chroot"
    www: "/var/www"
    config: "config"
    production: "production"
    testing: "testing"
    updates: "updates"
  files:
    archive_backend: "mbcabapi.tar.gz"
    update_backend: "mbcabapi_update.sh"
    testing_backend: "mbcabapi_testing.sh"
    config: "config.xml"
    log_main: "mbcabapi.log"
    log_debug: "mbcabapi.debug"
    log_update: "update.log"
  requirements:
    ram: 1864
    cores: 2
