mbcabinet:
  software:
    database:
      mysql_user: "mbcabinet"
      mysql_role: "role_mbcabinet"
      # Пароль пользователя
      # если пароль указан, то он будет использоваться при попытке подключения к базе (пользователь должен быть создан заранее)
      # если значение пустое, пароль будет сгенерирован (если база данных на одном сервере с модулем)
      mysql_pass: ""
      # адрес с которого будет подключаться модуль к MySQL серверу
      client_ip: "127.0.0.1"
      # взять IP адрес из переменной ansible_default_ipv4, в таком слчаи client_ip будет проигнорирован
      use_ansible_default_ipv4: true
    nginx:
      subdomain:
        # поддомен админки, если основной домен ispnet.demo
        # то получится:
        #   рабочая версия: stat.ispnet.demo
        #   тестовая версия: test.stat.ispnet.demo
        production: "stat"
        testing: "test.stat"
    fpm:
      production:
        pool_name: "mbcabinet_production"
        pool_file: "mbcabinet_production.conf"
        socket: "/var/run/php-fpm_mbcabinet_production.sock"
      testing:
        pool_name: "mbcabinet_testing"
        pool_file: "mbcabinet_testing.conf"
        socket: "/var/run/php-fpm_mbcabinet_testing.sock"
  dirs:
    module: "mbcabinet"
    chroot: "chroot"
    www: "/var/www"
    config: "config"
    production: "production"
    testing: "testing"
    updates: "updates"
  files:
    archive_backend: "mbcabinet.tar.gz"
    update_backend: "mbcabinet_update.sh"
    testing_backend: "mbcabinet_testing.sh"
    config: "config.xml"
    log_main: "mbcabinet.log"
    log_debug: "mbcabinet.debug"
    log_update: "update.log"
  requirements:
    ram: 1864
    cores: 2
