mbcore:
  system_user: "mbcore"
  software:
    database:
      mysql_user: "mbcore"
      mysql_role: "role_mbcore"
      # Пароль пользователя
      # если пароль указан, то он будет использоваться при попытке подключения к базе (пользователь должен быть создан заранее)
      # если значение пустое, пароль будет сгенерирован (если база данных на одном сервере с модулем)
      mysql_pass: ""
      # адрес с которого будет подключаться модуль к MySQL серверу
      client_ip: "127.0.0.1"
      # взять IP адрес из переменной ansible_default_ipv4, в таком слчаи client_ip будет проигнорирован
      use_ansible_default_ipv4: true
  params:
    production:
      ip: "127.0.0.1"
      port: "22007"
      pid: "/var/run/mbcore/mbcore_production.pid"
    testing:
      ip: "127.0.0.1"
      port: "22008"
      pid: "/var/run/mbcore/mbcore_testing.pid"
  dirs:
    module: "mbcore"
    config: "config"
    production: "production"
    testing: "testing"
    updates: "updates"
  files:
    systemd_production_service: "mbcore.service"
    systemd_testing_service: "mbcore_testing.service"
    pid_file: ""
    pid_testing_file: ""
    kernel: "mbcore.tar.gz"
    updates: "mbcore_update.sh"
    testing: "mbcore_testing.sh"
    config: "config.xml"
    log_main: "mbcore.log"
    log_debug: "mbcore.debug"
    log_update: "update.log"
  requirements:
    ram: 1864
    cores: 2
