mbnotify:
  system_user: "mbnotify"
  software:
    database:
      mysql_user: "mbnotify"
      mysql_role: "role_mbnotify"
      # Пароль пользователя
      # если пароль указан, то он будет использоваться при попытке подключения к базе (пользователь должен быть создан заранее)
      # если значение пустое, пароль будет сгенерирован (если база данных на одном сервере с модулем)
      mysql_pass: ""
      # адрес с которого будет подключаться модуль к MySQL серверу
      client_ip: "127.0.0.1"
      # взять IP адрес из переменной ansible_default_ipv4, в таком слчаи client_ip будет проигнорирован
      use_ansible_default_ipv4: true
  params:
    production:
      ip: "127.0.0.1"
      port: "22030"
      pid: "/var/run/mbnotify/mbnotify_production.pid"
    testing:
      ip: "127.0.0.1"
      port: "22031"
      pid: "/var/run/mbnotify/mbnotify_testing.pid"
  dirs:
    module: "mbnotify"
    config: "config"
    production: "production"
    testing: "testing"
    updates: "updates"
  files:
    systemd_production_service: "mbnotify.service"
    systemd_testing_service: "mbnotify_testing.service"
    archive: "mbnotify.tar.gz"
    updates: "mbnotify_update.sh"
    testing: "mbnotify_testing.sh"
    config: "config.xml"
    log_main: "mbnotify.log"
    log_debug: "mbnotify.debug"
    log_update: "update.log"
  requirements:
    ram: 512
    cores: 1
