mbstat:
  software:
    database:
      mysql_user: "mbstat"
      mysql_role: "role_mbstat"
      # Пароль пользователя
      # если пароль указан, то он будет использоваться при попытке подключения к базе (пользователь должен быть создан заранее)
      # если значение пустое, пароль будет сгенерирован (если база данных на одном сервере с модулем)
      mysql_pass: ""
      # адрес с которого будет подключаться модуль к MySQL серверу
      client_ip: "127.0.0.1"
      # взять IP адрес из переменной ansible_default_ipv4, в таком слчаи client_ip будет проигнорирован
      use_ansible_default_ipv4: true
    nginx:
      subdomain:
        # поддомен админки, если основной домен ispnet.demo
        # то получится:
        #   рабочая версия: stat.ispnet.demo
        #   тестовая версия: test.stat.ispnet.demo
        production: "stat"
        testing: "test.stat"
    fpm:
      production:
        pool_name: "mbstat_production"
        pool_file: "mbstat_production.conf"
        socket: "/var/run/php-fpm_mbstat_production.sock"
      testing:
        pool_name: "mbstat_testing"
        pool_file: "mbstat_testing.conf"
        socket: "/var/run/php-fpm_mbstat_testing.sock"
  dirs:
    module: "mbstat"
    chroot: "chroot"
    www: "/var/www"
    config: "config"
    production: "production"
    testing: "testing"
    updates: "updates"
  files:
    archive_backend: "mbstat.tar.gz"
    update_backend: "mbstat_update.sh"
    testing_backend: "mbstat_testing.sh"
    config: "config.xml"
    log_main: "mbstat.log"
    log_debug: "mbstat.debug"
    log_update: "update.log"
  requirements:
    ram: 1864
    cores: 2
