mbtvdaemon:
  system_user: "mbtvdaemon"
  software:
    database:
      mysql_user: "mbtvdaemon"
      mysql_role: "role_mbtvdaemon"
      # Пароль пользователя
      # если пароль указан, то он будет использоваться при попытке подключения к базе (пользователь должен быть создан заранее)
      # если значение пустое, пароль будет сгенерирован (если база данных на одном сервере с модулем)
      mysql_pass: ""
      # адрес с которого будет подключаться модуль к MySQL серверу
      client_ip: "127.0.0.1"
      # взять IP адрес из переменной ansible_default_ipv4, в таком слчаи client_ip будет проигнорирован
      use_ansible_default_ipv4: true
  params:
    production:
      ip: "127.0.0.1"
      port: "22050"
      pid: "/var/run/mbtvdaemon/mbtvdaemon_production.pid"
    testing:
      ip: "127.0.0.1"
      port: "22051"
      pid: "/var/run/mbtvdaemon/mbtvdaemon_testing.pid"
  dirs:
    module: "mbtvdaemon"
    config: "config"
    production: "production"
    testing: "testing"
    updates: "updates"
  files:
    event_scripts: [ "mb_event_device_add", "mb_event_device_del", "mb_event_iptv_add", "mb_event_iptv_del", "mb_event_iptv_disable", "mb_event_iptv_enable" ]
    systemd_production_service: "mbtvdaemon.service"
    systemd_testing_service: "mbtvdaemon_testing.service"
    archive: "mbtvdaemon.tar.gz"
    updates: "mbtvdaemon_update.sh"
    testing: "mbtvdaemon_testing.sh"
    config: "config.xml"
    log_main: "mbtvdaemon.log"
    log_debug: "mbtvdaemon.debug"
    log_update: "update.log"
  requirements:
    ram: 512
    cores: 1
