---
- name: "create {{ mbdaemonfinance.dirs.module }} catalogs"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - "{{ billing.dirs.home }}/license"
    - "{{ billing.dirs.home }}/{{ billing.dirs.files }}/{{ billing.dirs.scripts }}/{{ mbdaemonfinance.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonfinance.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ billing.dirs.backups }}/{{ mbdaemonfinance.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonfinance.dirs.module }}/{{ mbdaemonfinance.dirs.production }}/{{ mbdaemonfinance.dirs.config }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonfinance.dirs.module }}/{{ mbdaemonfinance.dirs.production }}/{{ mbdaemonfinance.dirs.updates }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonfinance.dirs.module }}/{{ mbdaemonfinance.dirs.testing }}/{{ mbdaemonfinance.dirs.config }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonfinance.dirs.module }}/{{ mbdaemonfinance.dirs.testing }}/{{ mbdaemonfinance.dirs.updates }}"
