---
- name: "add cron file"
  template:
    src: "module.cron"
    dest: "{{ OS.cron.dirs.custom }}/{{ mbdaemonfinance.dirs.module }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: "restart {{ OS.cron.name }} service"
  service:
    name: "{{ OS.cron.name }}"
    state: restarted
