---
- include_tasks: full_install.yml
  when: full_install is defined

- name: "module install"
  block:
    - include_tasks: mbadmin.yml
      when: mbadmin is defined

    - include_tasks: mbcabapi.yml
      when: mbcabapi is defined

    - include_tasks: mbcabinet.yml
      when: mbcabinet is defined

    - include_tasks: mbdaemoncore.yml
      when: mbdaemoncore is defined

    - include_tasks: mbcron.yml
      when: mbcron is defined

    - include_tasks: mbdaemonfinance.yml
      when: mbdaemonfinance is defined

    - include_tasks: mbdaemonmessenger.yml
      when: mbdaemonmessenger is defined

    - include_tasks: mbdaemonnotify.yml
      when: mbdaemonnotify is defined

    - include_tasks: mbhookpaygw.yml
      when: mbhookpaygw is defined

    - include_tasks: mbdaemonqueue.yml
      when: mbdaemonqueue is defined

    - include_tasks: mbradius.yml
      when: mbradius is defined

    - include_tasks: mbsql.yml
      when: mbsql is defined

    - include_tasks: mbdaemontv.yml
      when: mbdaemontv is defined

    - include_tasks: mbdaemonbot.yml
      when: mbdaemonbot is defined
  when: full_install is not defined
