---
- name: "update {{ mbpaygw.dirs.module }} {{ mbpaygw.dirs.production }}"
  command: "/bin/bash {{ mbpaygw.files.update_backend }}"
  args:
    chdir: "{{ billing.dirs.home }}/{{ mbpaygw.dirs.module }}/{{ mbpaygw.dirs.production }}/{{ mbpaygw.dirs.updates }}"
  ignore_errors: yes

- name: "update {{ mbpaygw.dirs.module }} {{ mbpaygw.dirs.testing }}"
  command: "/bin/bash {{ mbpaygw.files.testing_backend }}"
  args:
    chdir: "{{ billing.dirs.home }}/{{ mbpaygw.dirs.module }}/{{ mbpaygw.dirs.testing }}/{{ mbpaygw.dirs.updates }}"
  ignore_errors: yes
