---
- name: "copy {{ mbpaygw.dirs.module }} backend archive"
  copy:
    src: "{{ mbpaygw.files.archive_backend }}"
    dest: "{{ billing.dirs.tmp }}/{{ mbpaygw.files.archive_backend }}"
    mode: u=rw,g=r,o=r

- name: "unpack {{ mbpaygw.dirs.module }} backend archive"
  unarchive:
    src: "{{ billing.dirs.tmp }}/{{ mbpaygw.files.archive_backend }}"
    dest: "{{ billing.dirs.home }}/{{ mbpaygw.dirs.module }}/{{ item }}/public/"
  with_items:
    - "{{ mbpaygw.dirs.production }}"
    - "{{ mbpaygw.dirs.testing }}"

- name: "create main log file"
  file:
    path: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbpaygw.dirs.module }}/{{ mbpaygw.files.log_main }}"
    state: touch
    owner: "{{ OS.fpm.config.pool.user }}"
    group: "{{ OS.fpm.config.pool.user }}"
    mode: u=rw,g=r,o=r

- name: "create debug log file"
  file:
    path: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbpaygw.dirs.module }}/{{ mbpaygw.files.log_debug }}"
    state: touch
    owner: "{{ OS.fpm.config.pool.user }}"
    group: "{{ OS.fpm.config.pool.user }}"
    mode: u=rw,g=r,o=r

- name: "create update log file"
  file:
    path: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbpaygw.dirs.module }}/{{ mbpaygw.files.log_update }}"
    state: touch
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: "add updater"
  template:
    src: "{{ item.src }}"
    dest: "{{ billing.dirs.home }}/{{ mbpaygw.dirs.module }}/{{ item.path }}/{{ mbpaygw.dirs.updates }}/{{ item.dest }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - { src: "update_production.sh", dest: "{{ mbpaygw.files.update_backend }}", path: "{{ mbpaygw.dirs.production }}" }
    - { src: "update_testing.sh", dest: "{{ mbpaygw.files.testing_backend }}", path: "{{ mbpaygw.dirs.testing }}" }
