---
- name: "create {{ mbdaemonqueue.dirs.module }} catalogs"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - "{{ billing.dirs.home }}/license"
    - "{{ billing.dirs.home }}/{{ billing.dirs.files }}/{{ billing.dirs.scripts }}/{{ mbdaemonqueue.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonqueue.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ billing.dirs.backups }}/{{ mbdaemonqueue.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.dirs.production }}/{{ mbdaemonqueue.dirs.config }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.dirs.production }}/{{ mbdaemonqueue.dirs.updates }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.dirs.testing }}/{{ mbdaemonqueue.dirs.config }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.dirs.testing }}/{{ mbdaemonqueue.dirs.updates }}"
