---
- name: "replace {{ mbdaemonqueue.dirs.production }} cofig values"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.dirs.production }}/{{ mbdaemonqueue.dirs.config }}/{{ mbdaemonqueue.files.config }}"
    regexp: "{{ item.name }}"
    replace: "{{ item.value }}"
  with_items:
    - { name: '{server_host}', value: "{{ billing.mysql_server }}" }
    - { name: '{username}', value: "{{ mbdaemonqueue.software.database.mysql_user }}" }
    - { name: '{database}', value: "{{ mysql.database }}" }
    - { name: '{log_general}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.files.log_main }}" }
    - { name: '{log_debug}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.files.log_debug }}" }
    - { name: '{timezone}', value: "{{ timezone.stdout }}" }
    - { name: '{mbdaemonqueue_pid}', value: "{{ mbdaemonqueue.params.production.pid }}" }

- name: "replace mysql password"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.dirs.production }}/{{ mbdaemonqueue.dirs.config }}/{{ mbdaemonqueue.files.config }}"
    regexp: "{password}"
    replace: "{{ mbdaemonqueue.software.database.mysql_pass }}"
  when: mbdaemonqueue.software.database.mysql_pass != ""
  no_log: true

- name: "replace {{ mbdaemonqueue.dirs.testing }} cofig values"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.dirs.testing }}/{{ mbdaemonqueue.dirs.config }}/{{ mbdaemonqueue.files.config }}"
    regexp: "{{ item.name }}"
    replace: "{{ item.value }}"
  with_items:
    - { name: '{server_host}', value: "{{ billing.mysql_server }}" }
    - { name: '{username}', value: "{{ mbdaemonqueue.software.database.mysql_user }}" }
    - { name: '{database}', value: "{{ mysql.testing }}" }
    - { name: '{log_general}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.files.log_main }}" }
    - { name: '{log_debug}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.files.log_debug }}" }
    - { name: '{timezone}', value: "{{ timezone.stdout }}" }
    - { name: '{kernel_pid}', value: "{{ mbdaemonqueue.params.testing.pid }}" }

- name: "replace mysql password"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbdaemonqueue.dirs.module }}/{{ mbdaemonqueue.dirs.testing }}/{{ mbdaemonqueue.dirs.config }}/{{ mbdaemonqueue.files.config }}"
    regexp: "{password}"
    replace: "{{ mbdaemonqueue.software.database.mysql_pass }}"
  when: mbdaemonqueue.software.database.mysql_pass != ""
  no_log: true
