---
- name: "create {{ mbdaemonfiscalization.dirs.module }} catalogs"
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  with_items:
    - "{{ billing.dirs.home }}/license"
    - "{{ billing.dirs.home }}/{{ billing.dirs.files }}/{{ billing.dirs.scripts }}/{{ mbdaemonfiscalization.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbdaemonfiscalization.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ billing.dirs.backups }}/{{ mbdaemonfiscalization.dirs.module }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonfiscalization.dirs.module }}/{{ mbdaemonfiscalization.dirs.production }}/{{ mbdaemonfiscalization.dirs.config }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonfiscalization.dirs.module }}/{{ mbdaemonfiscalization.dirs.production }}/{{ mbdaemonfiscalization.dirs.updates }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonfiscalization.dirs.module }}/{{ mbdaemonfiscalization.dirs.testing }}/{{ mbdaemonfiscalization.dirs.config }}"
    - "{{ billing.dirs.home }}/{{ mbdaemonfiscalization.dirs.module }}/{{ mbdaemonfiscalization.dirs.testing }}/{{ mbdaemonfiscalization.dirs.updates }}"
