---
- name: "add logrotate file"
  template:
    src: "module.logrotate"
    dest: "{{ OS.logrotate }}/{{ mbdaemonfiscalization.dirs.module }}"
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
