---
- name: "replace {{ mbmessenger.dirs.production }} cofig values"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbmessenger.dirs.module }}/{{ mbmessenger.dirs.production }}/{{ mbmessenger.dirs.config }}/{{ mbmessenger.files.config }}"
    regexp: "{{ item.name }}"
    replace: "{{ item.value }}"
  with_items:
    - { name: '{server_host}', value: "{{ billing.mysql_server }}" }
    - { name: '{username}', value: "{{ mbmessenger.software.database.mysql_user }}" }
    - { name: '{database}', value: "{{ mysql.database }}" }
    - { name: '{log_general}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbmessenger.dirs.module }}/{{ mbmessenger.files.log_main }}" }
    - { name: '{log_debug}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbmessenger.dirs.module }}/{{ mbmessenger.files.log_debug }}" }
    - { name: '{timezone}', value: "{{ timezone.stdout }}" }
    - { name: '{mbmessenger_pid}', value: "{{ mbmessenger.params.production.pid }}" }
    - { name: '{mbmessenger_ip}', value: "{{ mbmessenger.params.production.ip }}" }
    - { name: '{mbmessenger_port}', value: "{{ mbmessenger.params.production.port }}" }

- name: "replace mysql password"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbmessenger.dirs.module }}/{{ mbmessenger.dirs.production }}/{{ mbmessenger.dirs.config }}/{{ mbmessenger.files.config }}"
    regexp: "{password}"
    replace: "{{ mbmessenger.software.database.mysql_pass }}"
  when: mbmessenger.software.database.mysql_pass != ""
  no_log: true

- name: "replace {{ mbmessenger.dirs.testing }} cofig values"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbmessenger.dirs.module }}/{{ mbmessenger.dirs.testing }}/{{ mbmessenger.dirs.config }}/{{ mbmessenger.files.config }}"
    regexp: "{{ item.name }}"
    replace: "{{ item.value }}"
  with_items:
    - { name: '{server_host}', value: "{{ billing.mysql_server }}" }
    - { name: '{username}', value: "{{ mbmessenger.software.database.mysql_user }}" }
    - { name: '{database}', value: "{{ mysql.testing }}" }
    - { name: '{log_general}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbmessenger.dirs.module }}/{{ mbmessenger.files.log_main }}" }
    - { name: '{log_debug}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbmessenger.dirs.module }}/{{ mbmessenger.files.log_debug }}" }
    - { name: '{timezone}', value: "{{ timezone.stdout }}" }
    - { name: '{mbmessenger_pid}', value: "{{ mbmessenger.params.testing.pid }}" }
    - { name: '{mbmessenger_ip}', value: "{{ mbmessenger.params.production.ip }}" }
    - { name: '{mbmessenger_port}', value: "{{ mbmessenger.params.production.port }}" }

- name: "replace mysql password"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbmessenger.dirs.module }}/{{ mbmessenger.dirs.testing }}/{{ mbmessenger.dirs.config }}/{{ mbmessenger.files.config }}"
    regexp: "{password}"
    replace: "{{ mbmessenger.software.database.mysql_pass }}"
  when: mbmessenger.software.database.mysql_pass != ""
  no_log: true
