---
- name: "configure php.ini CLI"
  replace:
     path: "{{ item.file }}"
     regexp: "{{ item.before }}"
     replace: "{{ item.after }}"
  loop:
    - { file: "{{ OS.php.dirs.conf }}/{{ OS.php.files.cli }}", before: "^register_argc_argv = Off", after: "register_argc_argv = On" }
    - { file: "{{ OS.php.dirs.conf }}/{{ OS.php.files.cli }}", before: "^;date.timezone =", after: "date.timezone = {{ timezone.stdout }}" }

- name: "configure php.ini FPM"
  replace:
     path: "{{ item.file }}"
     regexp: "{{ item.before }}"
     replace: "{{ item.after }}"
  loop:
    - { file: "{{ OS.fpm.dirs.conf }}/{{ OS.fpm.files.ini }}", before: "^register_argc_argv = Off", after: "register_argc_argv = On"  }
    - { file: "{{ OS.fpm.dirs.conf }}/{{ OS.fpm.files.ini }}", before: "^;date.timezone =", after: "date.timezone = {{ timezone.stdout }}" }

- name: "Disable php functions (cli)"
  become: true
  lineinfile:
    dest: "{{ OS.php.dirs.conf }}/{{ OS.php.files.cli }}"
    regexp: "disable_functions ="
    line: "disable_functions = {{ billing.disabled_functions }}"
