---
- name: "sysctl disable_ipv6"
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

- name: "sysctl vm.swappiness"
  sysctl:
    name: "vm.swappiness"
    value: '10'
    state: present
  when: '"-pve" not in ansible_kernel'
