---
- name: "replace {{ mbworkerbot.dirs.production }} cofig values"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbworkerbot.dirs.module }}/{{ mbworkerbot.dirs.production }}/{{ mbworkerbot.dirs.config }}/{{ mbworkerbot.files.config }}"
    regexp: "{{ item.name }}"
    replace: "{{ item.value }}"
  with_items:
    - { name: '{server_host}', value: "{{ billing.mysql_server }}" }
    - { name: '{username}', value: "{{ mbworkerbot.software.database.mysql_user }}" }
    - { name: '{database}', value: "{{ mysql.database }}" }
    - { name: '{log_general}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbworkerbot.dirs.module }}/{{ mbworkerbot.files.log_main }}" }
    - { name: '{log_debug}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbworkerbot.dirs.module }}/{{ mbworkerbot.files.log_debug }}" }
    - { name: '{timezone}', value: "{{ timezone.stdout }}" }
    - { name: '{mbworkerbot_pid}', value: "{{ mbworkerbot.params.production.pid }}" }
    - { name: '{mbworkerbot_ip}', value: "{{ mbworkerbot.params.production.ip }}" }
    - { name: '{mbworkerbot_port}', value: "{{ mbworkerbot.params.production.port }}" }

- name: "replace mysql password"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbworkerbot.dirs.module }}/{{ mbworkerbot.dirs.production }}/{{ mbworkerbot.dirs.config }}/{{ mbworkerbot.files.config }}"
    regexp: "{password}"
    replace: "{{ mbworkerbot.software.database.mysql_pass }}"
  when: mbworkerbot.software.database.mysql_pass != ""
  no_log: true

- name: "replace {{ mbworkerbot.dirs.testing }} cofig values"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbworkerbot.dirs.module }}/{{ mbworkerbot.dirs.testing }}/{{ mbworkerbot.dirs.config }}/{{ mbworkerbot.files.config }}"
    regexp: "{{ item.name }}"
    replace: "{{ item.value }}"
  with_items:
    - { name: '{server_host}', value: "{{ billing.mysql_server }}" }
    - { name: '{username}', value: "{{ mbworkerbot.software.database.mysql_user }}" }
    - { name: '{database}', value: "{{ mysql.testing }}" }
    - { name: '{log_general}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbworkerbot.dirs.module }}/{{ mbworkerbot.files.log_main }}" }
    - { name: '{log_debug}', value: "{{ billing.dirs.home }}/{{ billing.dirs.logs }}/{{ mbworkerbot.dirs.module }}/{{ mbworkerbot.files.log_debug }}" }
    - { name: '{timezone}', value: "{{ timezone.stdout }}" }
    - { name: '{mbworkerbot_pid}', value: "{{ mbworkerbot.params.testing.pid }}" }
    - { name: '{mbworkerbot_ip}', value: "{{ mbworkerbot.params.production.ip }}" }
    - { name: '{mbworkerbot_port}', value: "{{ mbworkerbot.params.production.port }}" }

- name: "replace mysql password"
  replace:
    path: "{{ billing.dirs.home }}/{{ mbworkerbot.dirs.module }}/{{ mbworkerbot.dirs.testing }}/{{ mbworkerbot.dirs.config }}/{{ mbworkerbot.files.config }}"
    regexp: "{password}"
    replace: "{{ mbworkerbot.software.database.mysql_pass }}"
  when: mbworkerbot.software.database.mysql_pass != ""
  no_log: true
